# Generated by Django 2.0.2 on 2018-02-13 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_demo', '0002_aritcle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aritcle',
            new_name='Article',
        ),
    ]
