# Generated by Django 2.0.2 on 2018-02-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_demo', '0003_auto_20180213_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.TextField(blank=True, choices=[('teach', 'Teach'), ('life', 'Life')], max_length=5, null=True),
        ),
    ]
