# Generated by Django 2.0.2 on 2018-02-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_demo', '0004_article_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.TextField(blank=True, choices=[('life', 'Life'), ('teach', 'Teach')], max_length=5, null=True),
        ),
    ]
